### ISSUE TITLE
Attempting to add widgets to KDE panel freezes panel

### ISSUE THREAD

**Issue by matejdro** [avivace/dotfiles#30]
Not sure if this is the best place to ask this, but I figure people most knowledgeable with i3+KDE merging are here.

When I'm in i3, I cannot add any items to the KDE panel. When I right click on the panel and select "Add Widgets...", no widget picker pops up and whole panel freezes instead.

So to add widgets, I must disable i3, relogin into regular KDE environment, update widgets, re-enable i3 and then relogin again. I don't do this often, but it is still annoying.

Are there any KDE logs that I can fetch to diagnose this further?

This is with Manjaro, Plasma 5.17.5 and i3 4.18.

**Comment by avivace** [comment]
@matejdro Do you have any compositor active?

 I remember this happening, too. It probably went away with an update (but now I'm on 5.17 too and it's *not* happening)

**Comment by matejdro** [comment]
No I'm currently not running any compositor, at least I think (If I read correctly, KDE's compositor is not active when using i3 and I have not enabled any others).

**Comment by avivace** [comment]
You are right, if you didn't manually setup an additional compositor (such as `compton` or `picom`) you are not running any. 
One thing I'd try is running this setup with a clean i3 configuration (just kill the wallpaper, but don't set anything as floating) and see if it breaks.
You should be able to get logs about KDE/plasma with something like this:
`journalctl -f | grep --line-buffered kde`. Maybe try `plasmashell` instead of kde.

**Comment by matejdro** [comment]
I think this might have gotten fixed with the plasma update. I'm not experiencing it anymore on Plasma `5.18.3`.

Thanks for your help.

**Comment by ilya-zlobintsev** [comment]
The issue is fixed by using a compositor like picom, if anyone experiences this.
