### ISSUE TITLE
New KDE Update Brought Ugly Margin Above PlasmaShell

### ISSUE THREAD

**Issue by Zackhardtoname** [avivace/dotfiles#34]
I am using Arch, i3, and KDE together. It has worked relatively well

Today after the latest update, there's a black bar as in the image. I don't have it in my pure kde session but someone does in this [reddit post](https://www.reddit.com/r/kde/comments/kcdy8e/new_kde_update_brought_ugly_black_margin_above/). Do you by any chance know how to get rid of this? Thank you!

![image](https://user-images.githubusercontent.com/25935197/102036460-df8bd400-3d90-11eb-8df1-b04a432f047d.png)
New KDE Update Brought Ugly Margin Above PlasmaShell

The cloest I have found, not quite the same, is this https://wiki.archlinux.org/index.php/KDE#Disable_panel_shadow. I've tried both suggested approaches but they don't work... (manual clicking related areas and run it as a script in my Downloads folder)

**Comment by avivace** [comment]
> Go to Display and Monitor > Compositor, and make sure the compositor is on. Mine had been turned off because OpenGL 2.0 had apparently caused KWin to crash in the past. I switched it to 3.1, hopefully won't have anymore problems.
The black margins are actually built into the "breeze" themes, seemingly as a replacement for compositor edge shadowing effects if the compositor is turned off (presumably added in last update) but I agree they look terrible. If turning the compositor on is not an option for you, because of performance or stability, you could try using a different theme.

Source: https://www.reddit.com/r/kde/comments/kcdy8e/new_kde_update_brought_ugly_black_margin_above/
